---
- hosts: localhost
  tasks:
          - name: Good Task
            command: date
            register: command_output
          - name: Print output
            debug:
                    msg: "{{command_output}}"
